FROM node:latest AS node_runner

WORKDIR /app
COPY ./src /app/src
COPY ./public /app/public
COPY ./package.json /app/package.json
COPY ./tsconfig.json /app/tsconfig.json
COPY ./.env /app/.env

RUN npm install

EXPOSE 3000

CMD ["npm", "start"]