
services:
  frontend:
    build:
      context: ./site
      dockerfile: Dockerfile.frontend
    container_name: flycierge-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: flycierge-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flycierge_db
      - SPRING_DATASOURCE_USERNAME=flycierge_user 
      - SPRING_DATASOURCE_PASSWORD=flycierge_pass
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: postgres
    container_name: db
    volumes:
      - ./db/docker_dumps:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=flycierge_user
      - POSTGRES_PASSWORD=flycierge_pass
      - POSTGRES_DB=flycierge_db